"use client";
import {useState} from "react";
import {MOCK_AI_PREDICTIONS,MOCK_DBSCAN_CLUSTERS} from "@/lib/referenceData";

type Area={name:string;heat:number;green:number;built:number;change:number;status:string};
type Role="bappeda"|"dlh"|"peneliti"|"admin";
export type ValidationInput={area:string;sourceUrl:string;dataPeriod:string;method:string;metric:string;finding:string;recommendation:"layak ditinjau"|"perlu perbaikan"};

export default function AnalysisWorkspace({areas,selected,onSelect,role,onPlanning,onMitigation,onSaveDraft,onValidate}:{areas:Area[];selected:string;onSelect:(name:string)=>void;role:Role;onPlanning:()=>void;onMitigation:()=>void;onSaveDraft:()=>void;onValidate:(input:ValidationInput)=>boolean}){
  const [scenario,setScenario]=useState<"dasar"|"rth">("dasar");
  const area=areas.find(item=>item.name===selected)??areas[0];
  const prediction=MOCK_AI_PREDICTIONS.find(item=>item.wilayah===selected);
  const cluster=MOCK_DBSCAN_CLUSTERS.find(item=>item.districts.includes(selected));
  const ranked=[...areas].sort((a,b)=>b.heat-a.heat);
  const rank=ranked.findIndex(item=>item.name===selected)+1;
  const projected=prediction?Number(prediction.predictedLst2030)-(scenario==="rth"?1.8:0):null;
  return <main className="shell section analysis-workspace">
    <div className="analysis-heading"><div><span className="eyebrow">Analisis internal · {role.toUpperCase()}</span><h1>{role==="bappeda"?"Dari data capture ke arah perencanaan":"Analisis wilayah dan hasil model"}</h1><p className="lead">Telusuri masukan data, baca keluaran prediksi dan klaster, lalu periksa validasinya sebelum dipakai sebagai rujukan.</p></div><span className="analysis-demo-pill">Data & keluaran model demonstrasi</span></div>
    <nav className="analysis-flow" aria-label="Alur analisis"><span>01 Data capture</span><span>02 AI: prediksi & klaster</span><span>03 Validasi</span><span>04 Keputusan</span></nav>
    <section className="analysis-source" aria-labelledby="analysis-source-title"><div><span className="eyebrow">01 / Capture</span><h2 id="analysis-source-title">Data yang masuk ke analisis</h2><p>Dataset titik perwakilan kecamatan periode 2025: suhu permukaan (LST), vegetasi, dan kawasan terbangun. Sumber yang ditampilkan adalah dataset demonstrasi ShadeMarang; belum ada pipeline citra satelit, BMKG, atau BPS yang aktif pada halaman ini.</p></div><label>Wilayah yang ditinjau<select className="field" value={selected} onChange={event=>onSelect(event.target.value)}>{areas.map(item=><option key={item.name}>{item.name}</option>)}</select></label></section>
    <section className="analysis-measures" aria-label="Indikator data capture"><div><span>LST titik contoh</span><strong>{area.heat.toFixed(1)}°C</strong><small>Peringkat {rank} dari {areas.length} titik</small></div><div><span>Tutupan vegetasi</span><strong>{area.green.toFixed(1)}%</strong><small>Indikator data contoh</small></div><div><span>Kawasan terbangun</span><strong>{area.built}%</strong><small>Indikator data contoh</small></div></section>
    <section className="analysis-ai" aria-labelledby="analysis-ai-title"><div className="analysis-section-head"><div><span className="eyebrow">02 / AI · keluaran referensi</span><h2 id="analysis-ai-title">Prediksi & clustering UHI</h2><p>Nilai berikut berasal dari keluaran contoh modul AI pada folder sumber proyek. Belum dihitung ulang dari data capture aktif; gunakan sebagai simulasi untuk meninjau alur keputusan.</p></div><span className="pill">Menunggu validasi data riil</span></div>
      <div className="analysis-ai-grid"><article className="analysis-prediction"><div className="spread"><div><span className="eyebrow">Prediksi LST · skenario</span><h3>{selected}</h3></div><strong className="analysis-prediction-value">{projected===null?"—":`${projected.toFixed(1)}°C`}</strong></div>{prediction?<><div className="analysis-time-line"><div><small>Capture contoh 2025</small><b>{area.heat.toFixed(1)}°C</b></div><div><small>Proyeksi referensi 2027</small><b>{scenario==="rth"?(Number(prediction.predictedLst2027)-0.9).toFixed(1):prediction.predictedLst2027}°C</b></div><div><small>Proyeksi referensi 2030</small><b>{projected?.toFixed(1)}°C</b></div></div><div className="analysis-scenario" role="group" aria-label="Skenario prediksi"><button className={scenario==="dasar"?"active":""} aria-pressed={scenario==="dasar"} onClick={()=>setScenario("dasar")}>Tanpa intervensi</button><button className={scenario==="rth"?"active":""} aria-pressed={scenario==="rth"} onClick={()=>setScenario("rth")}>Ilustrasi tambahan RTH</button></div><p className="small muted">Keluaran referensi memakai tahun dasar 2026, sedangkan capture di sini memakai data contoh 2025. Periode harus diselaraskan sebelum perbandingan. Pengurangan contoh 0,9°C (2027) dan 1,8°C (2030) bukan perhitungan model baru; metrik uji tidak dapat diverifikasi di aplikasi ini.</p></>:<p className="muted">Keluaran prediksi belum tersedia untuk wilayah ini. Data capture tetap dapat ditinjau.</p>}</article>
      <article className="analysis-cluster"><span className="eyebrow">Clustering spasial · contoh DBSCAN</span><h3>{cluster?cluster.name.split(" (")[0]:"Belum ada klaster"}</h3>{cluster?<><span className="pill">{cluster.priorityLevel}</span><p>Anggota klaster: {cluster.districts.join(", ")}.</p><div className="analysis-cluster-metrics"><span>LST rerata <b>{cluster.avgLst}°C</b></span><span>NDVI <b>{cluster.avgNdvi}</b></span><span>NDBI <b>{cluster.avgNdbi}</b></span></div><p><b>Hipotesis tindakan:</b> {cluster.suggestedAction}</p></>:<p>Klaster referensi belum tersedia untuk wilayah ini.</p>}<p className="small muted">Keanggotaan berasal dari data contoh, bukan hasil pengelompokan ulang saat wilayah dipilih.</p></article></div>
    </section>
    {role==="peneliti"&&<section className="research-validation" aria-labelledby="research-validation-title"><div><span className="eyebrow">03 / Peneliti · validasi internal</span><h2 id="research-validation-title">Catat pemeriksaan hasil AI</h2><p>Periksa kesesuaian periode, sumber data, metode, metrik uji, dan keterbatasan. Catatan dikirim untuk tinjauan reviewer; pengisian form tidak mengesahkan model atau menerbitkan hasil.</p></div><form className="form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);const saved=onValidate({area:selected,sourceUrl:String(data.get("sourceUrl")||""),dataPeriod:String(data.get("dataPeriod")||""),method:String(data.get("method")||""),metric:String(data.get("metric")||""),finding:String(data.get("finding")||""),recommendation:String(data.get("recommendation")) as ValidationInput["recommendation"]});if(saved)form.reset()}}><div className="grid two"><label>URL dataset / bukti uji<input className="field" type="url" name="sourceUrl" required placeholder="https://…"/></label><label>Periode data yang diuji<input className="field" name="dataPeriod" required placeholder="Contoh: 2024–2025"/></label><label>Metode dan versi model<input className="field" name="method" required placeholder="Contoh: Random Forest v2.1"/></label><label>Metrik hasil uji<input className="field" name="metric" required placeholder="Contoh: RMSE, MAE, Silhouette"/></label></div><label>Temuan dan keterbatasan<textarea className="field" name="finding" required placeholder="Jelaskan kesesuaian input, selisih hasil, dan keterbatasan data"/></label><label>Rekomendasi peneliti<select className="field" name="recommendation"><option value="perlu perbaikan">Perlu perbaikan</option><option value="layak ditinjau">Layak ditinjau reviewer</option></select></label><button className="btn primary" type="submit">Kirim catatan validasi untuk tinjau →</button></form></section>}
    <section className="analysis-bottom"><article><span className="eyebrow">03 / Pemeriksaan</span><h2>Validasi sebelum digunakan</h2><p>Status keluaran di halaman ini: <b>demonstrasi, belum tervalidasi terhadap data riil</b>. Peneliti perlu memeriksa kualitas input, periode pembanding, metrik model, dan hasil lapangan; reviewer menyetujui kajian sebelum BAPPEDA memakainya.</p><dl><div><dt>Sumber</dt><dd>Dataset demonstrasi ShadeMarang & keluaran contoh modul AI</dd></div><div><dt>Periode input</dt><dd>2025; proyeksi contoh 2027/2030</dd></div><div><dt>Metode yang dirancang</dt><dd>Random Forest (prediksi), DBSCAN (klaster)</dd></div><div><dt>Versi model aktif</dt><dd>Belum tersedia / belum terhubung</dd></div><div><dt>Keterbatasan</dt><dd>Titik skematis, angka contoh, tanpa validasi lapangan</dd></div></dl></article><article className="analysis-decision"><span className="eyebrow">04 / Pemakaian</span><h2>{role==="bappeda"?"Bahan perencanaan BAPPEDA":"Lanjutkan ke pengetahuan dan tindakan"}</h2><p>{role==="bappeda"?`Untuk ${selected}, bandingkan prioritas dan hipotesis klaster dengan kajian yang telah disetujui serta evaluasi DLH. Catat keputusan pada dokumen rujukan, bukan pada angka simulasi ini.`:"Simpan ringkasan sebagai draf kajian untuk diperiksa, atau tinjau tindakan yang terkait dengan wilayah."}</p><div className="analysis-actions">{role==="bappeda"?<><button className="btn primary" onClick={onPlanning}>Buka kajian & catat perencanaan →</button><button className="btn" onClick={onMitigation}>Lihat arahan mitigasi →</button></>:<><button className="btn primary" onClick={onMitigation}>Lihat mitigasi →</button>{(role==="peneliti"||role==="admin")&&<button className="btn" onClick={onSaveDraft}>Simpan draf analisis →</button>}</>}</div></article></section>
  </main>;
}
