"use client";

import {useMemo, useState} from "react";
import ThematicMap,{type AreaForMap} from "./ThematicMap";
import DashboardBelowMap from "./DashboardBelowMap";
import type {PlanningDecision} from "./planning";

type Area=AreaForMap&{change:number};
type Knowledge={id:string;title:string;summary:string;area:string;category:string;status:string};
type Action={id:string;title:string;area:string;status:string;kind:string};
type Evaluation={id:string;actionId:string;status:string;lesson:string};

export default function DashboardUhi({areas,knowledge,actions,evaluations,selected,onArea,onKnowledge,onAction,onMap,onAnalysis,onEvaluation,onAI,onPlanning,onMitigation,planningDecisions,role,internal}:{areas:Area[];knowledge:Knowledge[];actions:Action[];evaluations:Evaluation[];selected:string;onArea:(name:string)=>void;onKnowledge:(id:string)=>void;onAction:(id:string)=>void;onMap:()=>void;onAnalysis:()=>void;onEvaluation:()=>void;onAI:()=>void;onPlanning:()=>void;onMitigation:()=>void;planningDecisions:PlanningDecision[];role:string;internal:boolean}){
  const [layer,setLayer]=useState("Kondisi panas");
  const area=areas.find(a=>a.name===selected)??areas[0];
  const ranked=useMemo(()=>[...areas].sort((a,b)=>b.heat-a.heat),[areas]);
  const highest=ranked[0];
  const mean=areas.reduce((total,a)=>total+a.heat,0)/areas.length;
  const attention=areas.filter(a=>a.heat>=36).length;
  const relatedAction=actions.find(item=>item.area===selected);
  const approvedKnowledge=knowledge.filter(item=>item.status==="disetujui"||item.status==="dipublikasikan");
  const reviewedEvaluation=evaluations.filter(item=>item.status==="disetujui"||item.status==="dipublikasikan");
  const rthActions=actions.filter(item=>/rth|hijau|pohon|kanopi|taman/i.test(`${item.kind} ${item.title}`));
  const unevaluated=actions.filter(item=>item.status==="selesai"&&!evaluations.some(result=>result.actionId===item.id));
  const inReview=evaluations.filter(item=>item.status==="menunggu tinjau");
  const researchDocs=knowledge.filter(item=>item.category==="studi/kajian");
  const researchPending=researchDocs.filter(item=>item.status==="menunggu tinjau");

  return <main className="shell section dashboard-uhi">
    <div className="dashboard-intro"><div><span className="eyebrow">Dashboard UHI · {role==="bappeda"?"BAPPEDA":role==="dlh"?"DLH":role==="peneliti"?"Peneliti":"Kota Semarang"}</span><h1>{role==="bappeda"?"Dasar perencanaan wilayah":role==="dlh"?"Prioritas RTH dan tindakan":role==="peneliti"?"Kajian dan validasi UHI":"Pantauan panas perkotaan"}</h1><p className="lead">{role==="bappeda"?"Bandingkan wilayah, baca kajian tervalidasi, lalu catat arah tata ruang dan RTH.":role==="dlh"?"Temukan wilayah yang membutuhkan peneduhan, ikuti pekerjaan penghijauan, dan evaluasi tindakan selesai.":role==="peneliti"?"Tinjau data capture, periksa keluaran model, lalu kirim catatan validasi untuk reviewer.":"Mulai dari gambaran kota, pilih wilayah yang perlu diperhatikan, lalu ikuti pengetahuan dan riwayat tindakannya."}</p></div><div className="dashboard-period"><span className="eyebrow">Periode pengamatan</span><strong>2025</strong><span>Data contoh untuk eksplorasi KMS</span></div></div>

    <section className="dashboard-summary" aria-labelledby="dashboard-summary-title"><div className="dashboard-summary-main"><span className="eyebrow">Ringkasan kondisi UHI</span><h2 id="dashboard-summary-title">Pusat kota dan pesisir muncul sebagai prioritas pengamatan.</h2><p>Dalam data contoh, {attention} dari {areas.length} titik wilayah memiliki suhu permukaan setidaknya 36°C. Gunakan peta dan pengetahuan terkait untuk membaca konteksnya sebelum menentukan tindakan.</p><button className="btn primary" onClick={onMap}>Jelajahi seluruh peta <span aria-hidden="true">↗</span></button></div><div className="dashboard-summary-side"><span className="eyebrow">Titik paling panas</span><strong>{highest.heat.toFixed(1)}°C</strong><span>{highest.name}</span><button className="text-link" onClick={()=>{onArea(highest.name);onMap()}}>Baca kondisi wilayah →</button></div></section>

    <section className="dashboard-indicators" aria-label="Indikator utama"><div><span>Rerata titik pantau</span><strong>{mean.toFixed(1)}°C</strong><small>Contoh suhu permukaan</small></div><div><span>Perlu perhatian lebih</span><strong>{attention} wilayah</strong><small>Ambang contoh ≥ 36°C</small></div><div><span>Rentang antarwilayah</span><strong>{(highest.heat-ranked[ranked.length-1].heat).toFixed(1)}°C</strong><small>Tertinggi hingga terendah</small></div></section>

    {role==="bappeda"&&<section className="dashboard-role-panel" aria-labelledby="dashboard-planning-title"><div className="dashboard-role-lead"><span className="eyebrow">Ruang kerja BAPPEDA</span><h2 id="dashboard-planning-title">Kajian → arahan mitigasi → keputusan</h2><p>{approvedKnowledge.length} kajian tersedia untuk rujukan, {reviewedEvaluation.length} evaluasi telah disetujui, dan {planningDecisions.length} catatan perencanaan tersimpan. Gunakan semuanya untuk menentukan prioritas RTH atau tata ruang.</p><div className="dashboard-role-actions"><button className="btn primary" onClick={onMitigation}>Lihat arahan mitigasi →</button><button className="btn" onClick={onAnalysis}>Buka prediksi & klaster →</button><button className="btn" onClick={onPlanning}>Buka kajian & catat perencanaan →</button></div></div><div className="dashboard-role-evidence"><span className="small muted">Kajian untuk wilayah terpilih</span>{approvedKnowledge.filter(item=>item.area===selected||item.area==="Semua wilayah").slice(0,2).map(item=><button key={item.id} onClick={()=>onKnowledge(item.id)}>{item.title} ↗</button>)}<span className="small muted">Evaluasi yang telah disetujui</span>{reviewedEvaluation.slice(0,1).map(item=><button key={item.id} onClick={onEvaluation}>{item.lesson} ↗</button>)}</div></section>}
    {role==="dlh"&&<section className="dashboard-role-panel" aria-labelledby="dashboard-dlh-title"><div className="dashboard-role-lead"><span className="eyebrow">Ruang kerja DLH</span><h2 id="dashboard-dlh-title">RTH, pelaksanaan, dan evaluasi</h2><p>{rthActions.length} tindakan RTH atau penghijauan tercatat. {unevaluated.length} tindakan selesai perlu evaluasi, dan {inReview.length} evaluasi menunggu peninjauan.</p><div className="dashboard-role-actions"><button className="btn primary" onClick={onMitigation}>Kelola tindakan RTH →</button><button className="btn" onClick={onEvaluation}>Isi evaluasi →</button></div></div><div className="dashboard-role-evidence"><span className="small muted">Pekerjaan RTH</span>{rthActions.slice(0,2).map(item=><button key={item.id} onClick={()=>onAction(item.id)}>{item.title} · {item.status} ↗</button>)}{unevaluated.length>0&&<><span className="small muted">Perlu evaluasi</span><button onClick={onEvaluation}>{unevaluated[0].title} →</button></>}</div></section>}
    {role==="peneliti"&&<section className="dashboard-role-panel" aria-labelledby="dashboard-research-title"><div className="dashboard-role-lead"><span className="eyebrow">Ruang kerja peneliti</span><h2 id="dashboard-research-title">Data → kajian → validasi internal</h2><p>{researchDocs.length} kajian tercatat, {researchPending.length} menunggu tinjauan. Periksa bukti dan keterbatasan model sebelum mengirim penilaian; reviewer memutuskan kelayakan dokumen.</p><div className="dashboard-role-actions"><button className="btn primary" onClick={onAnalysis}>Periksa prediksi & klaster →</button><button className="btn" onClick={onPlanning}>Buka kajian →</button></div></div><div className="dashboard-role-evidence"><span className="small muted">Kajian dalam tinjauan</span>{researchPending.slice(0,2).map(item=><button key={item.id} onClick={()=>onKnowledge(item.id)}>{item.title} ↗</button>)}{researchPending.length===0&&<span className="small muted">Belum ada kajian yang menunggu tinjauan.</span>}</div></section>}

    <section className="section" aria-labelledby="dashboard-map-title"><div className="spread"><div><span className="eyebrow">Peta dan wilayah</span><h2 id="dashboard-map-title">Di mana perhatian dibutuhkan?</h2></div><label className="dashboard-layer">Lapisan peta<select className="field" value={layer} onChange={event=>setLayer(event.target.value)}><option>Kondisi panas</option><option>Vegetasi</option><option>Kawasan terbangun</option><option>Gabungan prioritas</option></select></label></div><div className="dashboard-map-layout"><div><ThematicMap areas={areas} selected={selected} onSelect={onArea} mode={layer} current={[]}/><p className="small muted dashboard-map-note">Peta dasar © OpenStreetMap. Lingkaran menunjukkan titik perwakilan kecamatan dari data contoh 2025, bukan batas wilayah presisi.</p></div><aside className="dashboard-area-detail" aria-live="polite"><span className="eyebrow">Wilayah terpilih</span><h3>{area.name}</h3><span className="pill">{area.status}</span><p>Suhu permukaan contoh <b>{area.heat.toFixed(1)}°C</b>. Tutupan vegetasi <b>{area.green.toFixed(1)}%</b> dan kawasan terbangun <b>{area.built}%</b> pada data demonstrasi.</p><div className="dashboard-area-links"><button onClick={onMap}>Lihat titik pada peta ↗</button>{relatedAction&&<button onClick={()=>onAction(relatedAction.id)}>{relatedAction.title} ↗</button>}</div><div className="dashboard-rank"><span className="eyebrow">Wilayah prioritas</span>{ranked.slice(0,4).map((item,index)=><button key={item.name} className={selected===item.name?"selected":""} onClick={()=>onArea(item.name)}><span>{String(index+1).padStart(2,"0")}</span><span>{item.name}</span><b>{item.heat.toFixed(1)}°</b></button>)}</div></aside></div></section>

    <DashboardBelowMap selected={selected} onSelect={onArea} knowledge={knowledge} actions={actions} internal={internal} role={role} onKnowledge={onKnowledge} onAction={onAction} onEvaluation={onEvaluation} onAI={onAI} onAnalysis={onAnalysis}/>
  </main>;
}
