"use client";
import {useState} from "react";
import {MOCK_POST_MITIGATION_RECORDS} from "@/lib/referenceData";

type Evaluation={id:string;actionId:string;status:string;observedLst?:number;predictedLst?:number;comparisonSource?:string;before:string;after:string};
type Action={id:string;title:string;area:string};
export default function EvaluationAnomalyPanel({evaluations,actions,role,onOpen}:{evaluations:Evaluation[];actions:Action[];role:string;onOpen:(id:string)=>void}){
  const [example,setExample]=useState("pm-3");
  const record=MOCK_POST_MITIGATION_RECORDS.find(item=>item.id===example)!;
  const checked=evaluations.filter(item=>Number.isFinite(item.observedLst)&&Number.isFinite(item.predictedLst));
  return <section className="evaluation-ai" aria-labelledby="evaluation-ai-title"><div className="analysis-section-head"><div><span className="eyebrow">AI · evaluasi & feedback</span><h2 id="evaluation-ai-title">Deteksi anomali pascamitigasi</h2><p>Bandingkan LST terukur setelah tindakan dengan proyeksi pada periode dan metode yang sebanding. Selisih lebih dari 1,0°C menjadi sinyal untuk pemeriksaan petugas.</p></div><span className="pill">Pemeriksaan, bukan keputusan otomatis</span></div>
    <div className="evaluation-ai-grid"><div><span className="eyebrow">Evaluasi yang tersimpan di KMS</span>{checked.length?checked.map(item=>{const action=actions.find(a=>a.id===item.actionId);const delta=Number(item.observedLst)-Number(item.predictedLst);return <button className="evaluation-anomaly-row" key={item.id} onClick={()=>onOpen(item.id)}><span><strong>{action?.title??"Tindakan"}</strong><small>{action?.area} · {item.before} → {item.after}</small></span><span className={Math.abs(delta)>1?"anomaly-flag":"anomaly-ok"}>{Math.abs(delta)>1?"Perlu verifikasi":"Dalam ambang"} · {delta>0?"+":""}{delta.toFixed(1)}°C</span></button>}):<div className="analysis-empty"><b>Belum ada pasangan angka untuk diuji.</b><p>Evaluasi lama hanya berisi uraian atau periode. DLH dapat mencatat LST terukur dan proyeksi pembanding pada evaluasi baru; sistem tidak menebak angka yang hilang.</p></div>}</div>
    <div className="evaluation-example"><div className="spread"><span className="eyebrow">Contoh data referensi · terpisah dari evaluasi KMS</span><select className="field" aria-label="Contoh anomali" value={example} onChange={event=>setExample(event.target.value)}>{MOCK_POST_MITIGATION_RECORDS.map(item=><option key={item.id} value={item.id}>{item.wilayah}</option>)}</select></div><h3>{record.wilayah}</h3><div className="evaluation-comparison"><span>Proyeksi contoh <b>{record.aiPredictedLst}°C</b></span><span>Setelah tindakan <b>{record.lstAfter}°C</b></span><span>Selisih <b>{record.deviation>0?"+":""}{record.deviation.toFixed(1)}°C</b></span></div><p className={record.isAnomaly?"anomaly-flag":"anomaly-ok"}>{record.isAnomaly?"Anomali contoh: periksa sumber dan kondisi lapangan":"Contoh dalam ambang pemeriksaan"}</p><p className="small muted">Catatan referensi DLH: {record.dlhEvaluationNotes}</p></div></div>
    <div className="evaluation-feedback"><span className="eyebrow">Siklus umpan balik</span><ol><li>DLH memeriksa sumber angka, lokasi, musim, dan catatan lapangan, lalu mengirim evaluasi untuk tinjau.</li><li>Peneliti meninjau penyebab selisih serta kualitas data capture.</li><li>Reviewer menyetujui evaluasi dan membuat draf pembelajaran di Pengetahuan.</li><li>Model baru dilatih dan dibandingkan dengan versi lama di sistem model terpisah.</li></ol><p className="small muted">Aplikasi ini belum menjalankan pelatihan ulang atau memperbarui model secara otomatis. {role==="bappeda"?"BAPPEDA memakai evaluasi yang disetujui untuk merevisi catatan perencanaan.":"Hasil verifikasi menjadi masukan untuk pembaruan kajian dan rencana tindakan berikutnya."}</p></div>
  </section>;
}
