"use client";

import type {FormEvent} from "react";
import type {PlanningDecision} from "./planning";

type Area={name:string;heat:number;green:number;status:string};
type Action={id:string;title:string;area:string;kind:string;purpose:string;actor:string;date:string;status:string;reason:string};
type Evaluation={id:string;actionId:string;status:string;lesson:string};
type Knowledge={id:string;title:string;summary:string;area:string;category:string;status:string};
type Props={role:string;areas:Area[];actions:Action[];evaluations:Evaluation[];knowledge:Knowledge[];decisions:PlanningDecision[];onAction:(id:string)=>void;onKnowledge:(id:string)=>void;onPlanning:()=>void;onEvaluation:()=>void;onSubmitAction:(data:FormData)=>void};

export default function MitigationWorkspace({role,areas,actions,evaluations,knowledge,decisions,onAction,onKnowledge,onPlanning,onEvaluation,onSubmitAction}:Props){
 const internal=role!=="publik",canAct=role==="dlh"||role==="admin";
 const visibleActions=internal?actions:actions.filter(item=>item.status==="selesai");
 const rthActions=actions.filter(item=>/rth|hijau|pohon|kanopi|taman/i.test(`${item.kind} ${item.title}`));
 const unevaluated=actions.filter(item=>item.status==="selesai"&&!evaluations.some(evaluation=>evaluation.actionId===item.id));
 const priority=[...areas].sort((left,right)=>right.heat-left.heat).slice(0,3);
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();onSubmitAction(new FormData(event.currentTarget));event.currentTarget.reset()};

 return <main className="shell section mitigation-workspace">
  <span className="eyebrow">{role==="bappeda"?"BAPPEDA · perencanaan mitigasi":role==="dlh"?"DLH · pelaksanaan RTH":internal?"Ruang kerja mitigasi":"Mitigasi yang dipublikasikan"}</span>
  <h1>{role==="bappeda"?"Arahan mitigasi untuk perencanaan":role==="dlh"?"RTH & tindakan peneduhan":"Tindakan mitigasi"}</h1>
  <p className="lead">{role==="bappeda"?"Bandingkan wilayah prioritas dengan kajian tervalidasi dan riwayat tindakan sebelum mencatat arah tata ruang atau RTH.":role==="dlh"?"Kelola penghijauan dan peneduhan, ikuti status pekerjaan, lalu isi evaluasi setelah tindakan selesai.":"Telusuri tujuan, alasan, dan hasil tindakan yang telah dipublikasikan."}</p>

  {role==="bappeda"&&<><section className="mitigation-role-section" aria-labelledby="mitigation-priority-title"><div className="spread"><div><span className="eyebrow">Data contoh 2025 · perlu validasi lapangan</span><h2 id="mitigation-priority-title">Wilayah untuk ditinjau dalam rencana RTH</h2></div><button className="btn primary" onClick={onPlanning}>Buka kajian & catat perencanaan →</button></div><div className="mitigation-priority-list">{priority.map((area,index)=>{const source=knowledge.find(doc=>doc.area===area.name&&(doc.status==="disetujui"||doc.status==="dipublikasikan"));const previous=actions.find(action=>action.area===area.name);return <article key={area.name}><span className="mitigation-priority-index">{String(index+1).padStart(2,"0")}</span><div><h3>{area.name}</h3><p><b>Alasan awal:</b> suhu permukaan contoh {area.heat.toFixed(1)}°C; tutupan vegetasi {area.green.toFixed(1)}%. Angka ini membantu menetapkan wilayah kajian, bukan membuktikan penyebab tunggal.</p><div className="mitigation-links">{source&&<button className="text-link" onClick={()=>onKnowledge(source.id)}>Kajian: {source.title} →</button>}{previous&&<button className="text-link" onClick={()=>onAction(previous.id)}>Riwayat: {previous.title} →</button>}</div></div></article>})}</div></section><section className="mitigation-role-section" aria-labelledby="mitigation-decision-title"><span className="eyebrow">Hasil pemakaian kajian</span><h2 id="mitigation-decision-title">Catatan perencanaan BAPPEDA</h2>{decisions.length?decisions.map(item=><article className="mitigation-decision" key={item.id}><span className="small muted">{item.area} · {new Date(item.createdAt).toLocaleDateString("id-ID")}</span><h3>{item.direction}</h3><p>{item.reason}</p><p className="small"><b>Tindak lanjut:</b> {item.followUp}</p>{knowledge.find(doc=>doc.id===item.documentId)&&<button className="text-link" onClick={()=>onKnowledge(item.documentId)}>Buka kajian rujukan →</button>}</article>):<p className="muted">Belum ada catatan. Pilih kajian tervalidasi untuk menyusun arah perencanaan.</p>}</section></>}

  {role==="dlh"&&<section className="mitigation-role-section" aria-labelledby="rth-work-title"><div className="spread"><div><span className="eyebrow">Ruang kerja DLH</span><h2 id="rth-work-title">Pekerjaan RTH & penghijauan</h2></div><span className="pill">{rthActions.length} tindakan terkait</span></div><p className="muted">Tinjau tujuan dan alasan tindakan, perbarui status pelaksanaan pada detail, lalu evaluasi hasilnya.</p><div className="rth-work-list">{rthActions.map(item=><button key={item.id} onClick={()=>onAction(item.id)}><span className="pill">{item.status}</span><strong>{item.title}</strong><span>{item.area} · {item.kind}</span><small>{item.purpose}</small></button>)}</div>{rthActions.length===0&&<p className="notice">Belum ada tindakan RTH. Gunakan formulir di bawah untuk mencatat pekerjaan pertama.</p>}{unevaluated.length>0&&<div className="notice rth-alert"><b>{unevaluated.length} tindakan selesai belum dievaluasi.</b> {unevaluated.map(item=>item.title).join(", ")}. <button className="text-link" onClick={onEvaluation}>Buka evaluasi →</button></div>}</section>}

  <section className="mitigation-role-section" aria-labelledby="mitigation-history-title"><span className="eyebrow">Riwayat pelaksanaan</span><h2 id="mitigation-history-title">Tindakan per wilayah</h2><div className="action-list">{visibleActions.map((item,index)=><button key={item.id} className="action-item" onClick={()=>onAction(item.id)}><span className="action-index">{String(index+1).padStart(2,"0")}</span><div className="action-main"><div className="action-status"><span className="pill">{item.status}</span>{internal&&item.status==="selesai"&&!evaluations.some(evaluation=>evaluation.actionId===item.id)&&<span className="pill warn">Belum dievaluasi</span>}</div><h3>{item.title}</h3><p>{item.purpose}</p><span className="muted small">{item.area} · {item.kind} · {item.actor} · {item.date}</span></div><span className="action-arrow" aria-hidden="true">↗</span></button>)}</div></section>

  {canAct&&<section className="mitigation-role-section" aria-labelledby="mitigation-new-title"><span className="eyebrow">DLH · catat pelaksanaan</span><h2 id="mitigation-new-title">Tambah tindakan RTH atau peneduhan</h2><form className="card form" onSubmit={submit}><label>Judul tindakan<input className="field" name="title" required/></label><div className="grid two"><label>Wilayah<select className="field" name="area" required>{areas.map(area=><option key={area.name}>{area.name}</option>)}</select></label><label>Jenis tindakan<select className="field" name="kind" required><option value="Penghijauan RTH">Penghijauan RTH</option><option value="Kanopi pohon">Kanopi pohon</option><option value="Peneduhan">Peneduhan</option><option value="Atap sejuk">Atap sejuk</option><option value="Perkerasan sejuk">Perkerasan sejuk</option></select></label><label>Pelaksana<input className="field" name="actor" required defaultValue="DLH Kota Semarang"/></label><label>Tanggal mulai<input className="field" type="date" name="date" required/></label></div><label>Tujuan<textarea className="field" name="purpose" required/></label><label>Mengapa tindakan ini dipilih?<textarea className="field" name="reason" required/></label><div className="notice small">Referensi yang dapat ditinjau: {knowledge.filter(doc=>doc.category==="hasil evaluasi"||doc.category==="pilihan mitigasi").map(doc=>doc.title).join(" · ")||"belum tersedia"}. Keputusan tindakan tetap dibuat oleh petugas.</div><button className="btn primary">Simpan tindakan</button></form></section>}
 </main>;
}
