"use client";

import {useMemo, useState} from "react";
import {Download, FileText, Search, Upload, X} from "lucide-react";
import type {PlanningDecision} from "./planning";

type KnowledgeDoc={id:string;title:string;summary:string;category:string;area:string;date:string;source:string;sourceUrl?:string;access:"publik"|"internal";status:string;body:string};
type Props={docs:KnowledgeDoc[];role:string;decisions:PlanningDecision[];onManage:()=>void;onApprove:(id:string)=>void;onPlan:(id:string,direction:string,reason:string,followUp:string)=>boolean};

const statusLabels:Record<string,string>={dipublikasikan:"Dipublikasikan",draf:"Draf Internal","menunggu tinjau":"Sedang Direview",disetujui:"Disetujui","perlu revisi":"Perlu Revisi"};
const pillars=["RTH & Kanopi Pohon","Material Cool Pavement","Desain Arsitektur Hijau","Regulasi & Kebijakan Wali Kota"];

export default function PrivateKnowledgePanel({docs,role,decisions,onManage,onApprove,onPlan}:Props){
 const [query,setQuery]=useState(""),[status,setStatus]=useState("semua"),[pillar,setPillar]=useState("semua"),[area,setArea]=useState("semua");
 const [selected,setSelected]=useState<KnowledgeDoc|null>(null),[planningDoc,setPlanningDoc]=useState<KnowledgeDoc|null>(null);
 const areas=[...new Set(docs.map(d=>d.area).filter(item=>item!=="Semua wilayah"))];
 const filtered=useMemo(()=>docs.filter(d=>{
  const text=`${d.title} ${d.summary} ${d.category} ${d.area}`.toLowerCase();
  return (!query||text.includes(query.toLowerCase()))&&(status==="semua"||d.status===status)&&(area==="semua"||d.area===area)&&(pillar==="semua"||text.includes(pillar.toLowerCase().split(" & ")[0]));
 }),[docs,query,status,pillar,area]);
 const exportIndex=()=>{
  const body=filtered.map(d=>`${d.title}\t${d.area}\t${statusLabels[d.status]||d.status}\t${d.sourceUrl||""}`).join("\n");
  const blob=new Blob([`Judul\tWilayah\tStatus\tSumber\n${body}`],{type:"text/tab-separated-values"});
  const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="indeks-sop-shademarang.tsv";link.click();URL.revokeObjectURL(url);
 };
 const downloadDocument=(doc:KnowledgeDoc)=>{
  const blob=new Blob([`${doc.title}\n\n${doc.body}`],{type:"text/plain"});
  const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${doc.id}-dokumen.txt`;link.click();URL.revokeObjectURL(url);
 };
 const startPlanning=(doc:KnowledgeDoc)=>{setSelected(null);setPlanningDoc(doc)};

 return <main className="shell section private-knowledge">
  <div className="knowledge-private-head"><div><span className="eyebrow">Basis pengetahuan · terproteksi</span><h1>Pustaka SOP & Mitigasi UHI</h1><p className="lead">{role==="bappeda"?"Baca kajian tervalidasi, lalu catat bagaimana hasilnya digunakan dalam perencanaan wilayah.":"Telusuri dokumen kerja berdasarkan status, pilar, dan wilayah."}</p></div><div className="knowledge-user-badge"><strong>{role==="admin"?"Administrator Sistem":role==="bappeda"?"Perencana BAPPEDA":role==="dlh"?"Staf DLH":"Peneliti"}</strong><span>{role==="admin"?"ShadeMarang KMS":role==="bappeda"?"BAPPEDA Kota Semarang":role==="dlh"?"DLH Kota Semarang":"Tim Peneliti"}</span><b>{role.toUpperCase()}</b></div></div>
  {role==="bappeda"&&<section className="planning-overview" aria-labelledby="planning-title"><div className="planning-overview-head"><div><span className="eyebrow">Kajian → perencanaan</span><h2 id="planning-title">Catatan keputusan BAPPEDA</h2><p>Pilih kajian di bawah, tinjau sumbernya, lalu catat arah perencanaan beserta alasan dan tindak lanjut.</p></div><span className="pill">{decisions.length} catatan</span></div>{decisions.length>0&&<div className="planning-list">{decisions.map(item=>{const source=docs.find(doc=>doc.id===item.documentId);return <article key={item.id}><span className="small muted">{item.area} · {new Date(item.createdAt).toLocaleDateString("id-ID")}</span><h3>{item.direction}</h3><p>{item.reason}</p><p className="small"><b>Tindak lanjut:</b> {item.followUp}</p><button className="text-link" onClick={()=>source&&setSelected(source)}>Rujukan: {source?.title||"Dokumen tidak tersedia"} →</button></article>})}</div>}</section>}
  {role!=="bappeda"&&<div className="knowledge-actions"><button className="btn primary" onClick={onManage}><Upload size={16}/> Tambah Dokumen</button><button className="btn" onClick={exportIndex}><Download size={16}/> Ekspor Indeks SOP</button></div>}
  <div className="knowledge-filters"><label><Search size={16}/><input aria-label="Cari SOP dan mitigasi" placeholder="Cari SOP, regulasi, atau mitigasi..." value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Status dokumen" value={status} onChange={event=>setStatus(event.target.value)}><option value="semua">Semua status</option>{Object.entries(statusLabels).filter(([key])=>role!=="bappeda"||key==="disetujui"||key==="dipublikasikan").map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="Pilar mitigasi" value={pillar} onChange={event=>setPillar(event.target.value)}><option value="semua">Semua pilar mitigasi</option>{pillars.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Wilayah" value={area} onChange={event=>setArea(event.target.value)}><option value="semua">Semua wilayah</option>{areas.map(item=><option key={item}>{item}</option>)}</select></div>
  <div className="knowledge-results-head"><span>{filtered.length} dokumen ditemukan</span><span className="muted small">Sumber dan status ditampilkan untuk audit</span></div>
  <div className="knowledge-doc-grid">{filtered.map(doc=><article className="knowledge-doc-card" key={doc.id}><div className="knowledge-doc-top"><span className={`status-pill status-${doc.status.replaceAll(" ","-")}`}>{statusLabels[doc.status]||doc.status}</span><span className="doc-code">SOP-{doc.access==="internal"?"INT":"PUB"}-{doc.id.toUpperCase()}</span></div><h2>{doc.title}</h2><p>{doc.summary}</p><div className="knowledge-doc-meta"><span>{doc.area}</span><span>{doc.date}</span><span>{doc.category}</span></div><div className="knowledge-doc-footer"><button className="text-link" onClick={()=>setSelected(doc)}><FileText size={15}/> Baca lengkap</button>{role==="bappeda"?<button className="text-link" onClick={()=>startPlanning(doc)}>Gunakan untuk perencanaan →</button>:doc.sourceUrl&&<a className="text-link" href={doc.sourceUrl} target="_blank" rel="noreferrer">Sumber URL ↗</a>}</div></article>)}</div>
  {filtered.length===0&&<div className="notice">Tidak ada dokumen yang cocok dengan filter ini.</div>}
  {selected&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><aside className="drawer knowledge-detail" role="dialog" aria-modal="true" aria-label={`Dokumen ${selected.title}`}><div className="spread"><span className="eyebrow">Detail dokumen · {statusLabels[selected.status]||selected.status}</span><button className="btn" onClick={()=>setSelected(null)}><X size={16}/> Tutup</button></div><div className="knowledge-detail-heading"><div className="knowledge-detail-badges"><span className={`status-pill status-${selected.status.replaceAll(" ","-")}`}>{statusLabels[selected.status]||selected.status}</span><span className="doc-code">SOP-{selected.access==="internal"?"INT":"PUB"}-{selected.id.toUpperCase()}</span></div><h2>{selected.title}</h2><p className="lead">{selected.summary}</p><div className="knowledge-detail-meta"><span>◉ {selected.source}</span><span>▣ {selected.date}</span><span>◷ 4 mnt baca</span></div></div><div className="knowledge-detail-scroll"><p style={{whiteSpace:"pre-wrap"}}>{selected.body}</p></div><div className="knowledge-detail-actions">{selected.sourceUrl&&<a className="btn primary" href={selected.sourceUrl} target="_blank" rel="noreferrer">Buka sumber lengkap ↗</a>}<button className="btn" onClick={()=>downloadDocument(selected)}><Download size={16}/> Unduh Dokumen</button>{role==="bappeda"&&<button className="btn" onClick={()=>startPlanning(selected)}>Gunakan untuk perencanaan →</button>}{role==="admin"&&selected.status!=="dipublikasikan"&&<button className="btn" onClick={()=>{onApprove(selected.id);setSelected({...selected,status:"dipublikasikan"})}}>Setujui publikasi</button>}<button className="btn primary" onClick={()=>setSelected(null)}>Tutup</button></div></aside></div>}
  {planningDoc&&role==="bappeda"&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setPlanningDoc(null)}}><div className="drawer planning-drawer" role="dialog" aria-modal="true" aria-labelledby="planning-form-title"><div className="spread"><span className="eyebrow">BAPPEDA · perencanaan internal</span><button className="btn" onClick={()=>setPlanningDoc(null)}><X size={16}/> Tutup</button></div><h2 id="planning-form-title">Gunakan kajian untuk perencanaan</h2><div className="planning-source"><span className="small muted">Kajian tervalidasi · {planningDoc.area}</span><strong>{planningDoc.title}</strong><p>{planningDoc.summary}</p>{planningDoc.sourceUrl&&<a href={planningDoc.sourceUrl} target="_blank" rel="noreferrer">Periksa sumber kajian ↗</a>}</div><form className="form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(onPlan(planningDoc.id,String(data.get("direction")||""),String(data.get("reason")||""),String(data.get("followUp")||"")))setPlanningDoc(null)}}><label>Arah perencanaan<input className="field" name="direction" required placeholder="Contoh: Prioritaskan koridor teduh"/></label><label>Alasan berdasarkan kajian<textarea className="field" name="reason" required placeholder="Jelaskan kondisi wilayah dan temuan yang menjadi dasar"/></label><label>Tindak lanjut yang diusulkan<textarea className="field" name="followUp" required placeholder="Contoh: koordinasi dengan DLH dan verifikasi lapangan"/></label><p className="small muted">Catatan ini adalah bahan perencanaan internal, bukan perubahan status tindakan DLH.</p><button className="btn primary" type="submit">Simpan catatan perencanaan</button></form></div></div>}
 </main>;
}
