"use client";

import {useMemo,useState} from "react";
import {BookOpen,Search,X} from "lucide-react";

type PublicDoc={id:string;title:string;summary:string;category:string;area:string;date:string;source:string;sourceUrl?:string;body:string};
export default function PublicKnowledgePanel({docs}:{docs:PublicDoc[]}){
 const [query,setQuery]=useState(""),[category,setCategory]=useState("semua"),[selected,setSelected]=useState<PublicDoc|null>(null);
 const categories=[...new Set(docs.map(d=>d.category))];
 const results=useMemo(()=>docs.filter(d=>{const text=`${d.title} ${d.summary} ${d.area} ${d.category}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(category==="semua"||d.category===category)}),[docs,query,category]);
 return <main className="shell section public-knowledge"><div className="public-knowledge-head"><div><span className="eyebrow">Pengetahuan publik · terverifikasi</span><h1>Temukan jawaban yang berkonteks</h1><p className="lead">Ringkasan kajian, tindakan, dan panduan UHI yang telah ditinjau untuk dibaca masyarakat.</p></div><span className="public-knowledge-mark"><BookOpen size={20}/> {docs.length} bacaan</span></div><div className="public-knowledge-search"><Search size={18}/><input aria-label="Cari pengetahuan UHI" placeholder="Cari penghijauan, wilayah panas, atau mitigasi..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="knowledge-tabs"><button className={category==="semua"?"active":""} onClick={()=>setCategory("semua")}>Semua</button>{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="public-knowledge-grid">{results.map(doc=><article className="public-knowledge-card" key={doc.id}><span className="status-pill status-dipublikasikan">Dipublikasikan</span><span className="doc-code">{doc.category}</span><h2>{doc.title}</h2><p>{doc.summary}</p><div className="knowledge-doc-meta"><span>{doc.area}</span><span>{doc.date}</span></div><button className="text-link" onClick={()=>setSelected(doc)}>Baca ringkasan lengkap →</button></article>)}</div>{results.length===0&&<div className="notice">Belum ada pengetahuan publik yang cocok.</div>}{selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="drawer public-knowledge-detail"><div className="spread"><span className="eyebrow">Pengetahuan terverifikasi</span><button className="btn" onClick={()=>setSelected(null)}><X size={16}/> Tutup</button></div><h2>{selected.title}</h2><p className="lead">{selected.summary}</p><p className="small muted">{selected.area} · {selected.date} · sumber: {selected.source}</p><div className="public-detail-body"><p style={{whiteSpace:"pre-wrap"}}>{selected.body}</p></div>{selected.sourceUrl&&<a className="btn primary" href={selected.sourceUrl} target="_blank" rel="noreferrer">Buka sumber lengkap ↗</a>}</aside></div>}</main>;
}
