import type { WilayahData, AIPredictionItem, DBSCANClusterItem, PostMitigationRecord } from './referenceTypes';

export const INITIAL_WILAYAH: WilayahData[] = [
  {
    id: 'w-1',
    wilayah: 'Semarang Tengah',
    kategori: 'Hotspot inti',
    lst: 38.4,
    ndvi: 0.11,
    ndbi: 0.38,
    status: 'Hotspot',
    vegetationCoverPct: 8.5,
    priorityRTH: 5,
    zoneType: 'Inti Perkotaan',
    populationDensity: 11200,
    hviScore: 88,
    elevationMeters: 8,
    imperviousSurfacePct: 89,
    areaKm2: 6.14,
    coordinates: '6.9827° S, 110.4203° E',
  },
  {
    id: 'w-2',
    wilayah: 'Semarang Utara',
    kategori: 'Hotspot pesisir',
    lst: 37.9,
    ndvi: 0.14,
    ndbi: 0.34,
    status: 'Hotspot',
    vegetationCoverPct: 10.2,
    priorityRTH: 5,
    zoneType: 'Pesisir Utara',
    populationDensity: 9800,
    hviScore: 84,
    elevationMeters: 3,
    imperviousSurfacePct: 85,
    areaKm2: 11.36,
    coordinates: '6.9602° S, 110.4225° E',
  },
  {
    id: 'w-3',
    wilayah: 'Semarang Timur',
    kategori: 'Hotspot inti',
    lst: 36.8,
    ndvi: 0.16,
    ndbi: 0.31,
    status: 'Hotspot',
    vegetationCoverPct: 12.0,
    priorityRTH: 4,
    zoneType: 'Inti Perkotaan',
    populationDensity: 10400,
    hviScore: 78,
    elevationMeters: 6,
    imperviousSurfacePct: 81,
    areaKm2: 7.70,
    coordinates: '6.9845° S, 110.4412° E',
  },
  {
    id: 'w-4',
    wilayah: 'Genuk',
    kategori: 'Hotspot industri',
    lst: 37.2,
    ndvi: 0.13,
    ndbi: 0.36,
    status: 'Hotspot',
    vegetationCoverPct: 9.8,
    priorityRTH: 5,
    zoneType: 'Industri Timur',
    populationDensity: 4500,
    hviScore: 82,
    elevationMeters: 2,
    imperviousSurfacePct: 83,
    areaKm2: 27.39,
    coordinates: '6.9610° S, 110.4780° E',
  },
  {
    id: 'w-5',
    wilayah: 'Semarang Selatan',
    kategori: 'Pemantauan',
    lst: 34.2,
    ndvi: 0.22,
    ndbi: 0.22,
    status: 'Hangat',
    vegetationCoverPct: 18.5,
    priorityRTH: 3,
    zoneType: 'Inti Perkotaan',
    populationDensity: 8900,
    hviScore: 62,
    elevationMeters: 22,
    imperviousSurfacePct: 72,
    areaKm2: 5.93,
    coordinates: '7.0012° S, 110.4241° E',
  },
  {
    id: 'w-6',
    wilayah: 'Gayamsari',
    kategori: 'Pemantauan',
    lst: 35.6,
    ndvi: 0.18,
    ndbi: 0.27,
    status: 'Hangat',
    vegetationCoverPct: 14.1,
    priorityRTH: 4,
    zoneType: 'Industri Timur',
    populationDensity: 7400,
    hviScore: 70,
    elevationMeters: 5,
    imperviousSurfacePct: 77,
    areaKm2: 6.18,
    coordinates: '6.9890° S, 110.4550° E',
  },
  {
    id: 'w-7',
    wilayah: 'Candisari',
    kategori: 'Elevasi sedang',
    lst: 33.1,
    ndvi: 0.28,
    ndbi: 0.15,
    status: 'Hangat',
    vegetationCoverPct: 24.0,
    priorityRTH: 2,
    zoneType: 'Perbukitan Selatan',
    populationDensity: 6700,
    hviScore: 52,
    elevationMeters: 95,
    imperviousSurfacePct: 62,
    areaKm2: 6.54,
    coordinates: '7.0210° S, 110.4280° E',
  },
  {
    id: 'w-8',
    wilayah: 'Semarang Barat',
    kategori: 'Normal',
    lst: 32.8,
    ndvi: 0.31,
    ndbi: 0.12,
    status: 'Neutral',
    vegetationCoverPct: 27.5,
    priorityRTH: 2,
    zoneType: 'Perumahan Barat',
    populationDensity: 7100,
    hviScore: 48,
    elevationMeters: 12,
    imperviousSurfacePct: 58,
    areaKm2: 21.74,
    coordinates: '6.9870° S, 110.3890° E',
  },
  {
    id: 'w-9',
    wilayah: 'Gajahmungkur',
    kategori: 'Perbukitan hijau',
    lst: 31.5,
    ndvi: 0.38,
    ndbi: 0.05,
    status: 'Neutral',
    vegetationCoverPct: 35.0,
    priorityRTH: 1,
    zoneType: 'Perbukitan Selatan',
    populationDensity: 4300,
    hviScore: 38,
    elevationMeters: 140,
    imperviousSurfacePct: 48,
    areaKm2: 9.07,
    coordinates: '7.0150° S, 110.4070° E',
  },
  {
    id: 'w-10',
    wilayah: 'Banyumanik',
    kategori: 'Elevasi tinggi',
    lst: 29.5,
    ndvi: 0.58,
    ndbi: -0.12,
    status: 'Neutral',
    vegetationCoverPct: 52.3,
    priorityRTH: 1,
    zoneType: 'Perbukitan Selatan',
    populationDensity: 5200,
    hviScore: 26,
    elevationMeters: 210,
    imperviousSurfacePct: 36,
    areaKm2: 25.69,
    coordinates: '7.0720° S, 110.4190° E',
  },
  {
    id: 'w-11',
    wilayah: 'Gunungpati',
    kategori: 'Konservasi hulu',
    lst: 28.8,
    ndvi: 0.65,
    ndbi: -0.18,
    status: 'Neutral',
    vegetationCoverPct: 64.0,
    priorityRTH: 1,
    zoneType: 'Perbukitan Selatan',
    populationDensity: 1800,
    hviScore: 21,
    elevationMeters: 260,
    imperviousSurfacePct: 26,
    areaKm2: 54.11,
    coordinates: '7.0850° S, 110.3720° E',
  },
  {
    id: 'w-12',
    wilayah: 'Mijen',
    kategori: 'Agroforestri',
    lst: 28.2,
    ndvi: 0.70,
    ndbi: -0.22,
    status: 'Neutral',
    vegetationCoverPct: 71.5,
    priorityRTH: 1,
    zoneType: 'Perumahan Barat',
    populationDensity: 1200,
    hviScore: 18,
    elevationMeters: 290,
    imperviousSurfacePct: 21,
    areaKm2: 57.55,
    coordinates: '7.0650° S, 110.3120° E',
  },
  {
    id: 'w-13',
    wilayah: 'Ngaliyan',
    kategori: 'Perbukitan barat & industri',
    lst: 31.8,
    ndvi: 0.42,
    ndbi: 0.08,
    status: 'Neutral',
    vegetationCoverPct: 42.0,
    priorityRTH: 2,
    zoneType: 'Perumahan Barat',
    populationDensity: 3600,
    hviScore: 42,
    elevationMeters: 85,
    imperviousSurfacePct: 52,
    areaKm2: 37.99,
    coordinates: '7.0050° S, 110.3450° E',
  },
  {
    id: 'w-14',
    wilayah: 'Tugu',
    kategori: 'Pesisir barat & mangrove',
    lst: 34.8,
    ndvi: 0.24,
    ndbi: 0.20,
    status: 'Hangat',
    vegetationCoverPct: 22.0,
    priorityRTH: 3,
    zoneType: 'Pesisir Utara',
    populationDensity: 2200,
    hviScore: 60,
    elevationMeters: 4,
    imperviousSurfacePct: 66,
    areaKm2: 31.78,
    coordinates: '6.9720° S, 110.3250° E',
  },
  {
    id: 'w-15',
    wilayah: 'Pedurungan',
    kategori: 'Permukiman padat timur',
    lst: 35.2,
    ndvi: 0.20,
    ndbi: 0.25,
    status: 'Hangat',
    vegetationCoverPct: 16.5,
    priorityRTH: 4,
    zoneType: 'Industri Timur',
    populationDensity: 8300,
    hviScore: 66,
    elevationMeters: 8,
    imperviousSurfacePct: 74,
    areaKm2: 20.72,
    coordinates: '7.0020° S, 110.4720° E',
  },
  {
    id: 'w-16',
    wilayah: 'Tembalang',
    kategori: 'Kawasan pendidikan tinggi',
    lst: 30.8,
    ndvi: 0.52,
    ndbi: -0.05,
    status: 'Neutral',
    vegetationCoverPct: 48.0,
    priorityRTH: 2,
    zoneType: 'Perbukitan Selatan',
    populationDensity: 4100,
    hviScore: 31,
    elevationMeters: 175,
    imperviousSurfacePct: 42,
    areaKm2: 44.20,
    coordinates: '7.0580° S, 110.4520° E',
  }
];

export const MOCK_AI_PREDICTIONS: AIPredictionItem[] = [
  {
    id: 'pred-1',
    wilayah: 'Semarang Tengah',
    historicalLst: 38.4,
    predictedLst2027: 39.1,
    predictedLst2030: 40.2,
    trend: 'Meningkat Tajam',
    modelConfidence: 93.8,
  },
  {
    id: 'pred-2',
    wilayah: 'Semarang Utara',
    historicalLst: 37.9,
    predictedLst2027: 38.5,
    predictedLst2030: 39.4,
    trend: 'Meningkat Tajam',
    modelConfidence: 91.5,
  },
  {
    id: 'pred-3',
    wilayah: 'Genuk',
    historicalLst: 37.2,
    predictedLst2027: 37.8,
    predictedLst2030: 38.9,
    trend: 'Meningkat Tajam',
    modelConfidence: 89.2,
  },
  {
    id: 'pred-4',
    wilayah: 'Semarang Timur',
    historicalLst: 36.8,
    predictedLst2027: 37.3,
    predictedLst2030: 38.1,
    trend: 'Meningkat Moderat',
    modelConfidence: 94.0,
  },
  {
    id: 'pred-5',
    wilayah: 'Gayamsari',
    historicalLst: 35.6,
    predictedLst2027: 36.0,
    predictedLst2030: 36.7,
    trend: 'Meningkat Moderat',
    modelConfidence: 92.1,
  },
  {
    id: 'pred-6',
    wilayah: 'Semarang Selatan',
    historicalLst: 34.2,
    predictedLst2027: 34.4,
    predictedLst2030: 34.9,
    trend: 'Stabil',
    modelConfidence: 95.4,
  }
];

// FR-09: DBSCAN Spatial Clusters
export const MOCK_DBSCAN_CLUSTERS: DBSCANClusterItem[] = [
  {
    clusterId: 0,
    name: 'Klaster 0: Hotspot Inti Komersial (High Thermal, Low NDVI)',
    districts: ['Semarang Tengah', 'Semarang Timur'],
    avgLst: 37.6,
    avgNdvi: 0.13,
    avgNdbi: 0.35,
    priorityLevel: 'Prioritas 1 (Kritis)',
    suggestedAction: 'Retrofit green roof gedung bertingkat, kanopi jalan protokol, albedo paving trotoar.'
  },
  {
    clusterId: 1,
    name: 'Klaster 1: Hotspot Pesisir & Logistik Pelabuhan',
    districts: ['Semarang Utara', 'Genuk'],
    avgLst: 37.5,
    avgNdvi: 0.13,
    avgNdbi: 0.38,
    priorityLevel: 'Prioritas 1 (Kritis)',
    suggestedAction: 'Pembangunan coastal green belt mangrove dan koridor ventilasi angin laut ke darat.'
  },
  {
    clusterId: 2,
    name: 'Klaster 2: Koridor Urban Transisi',
    districts: ['Semarang Selatan', 'Gayamsari', 'Semarang Barat', 'Candisari'],
    avgLst: 33.9,
    avgNdvi: 0.25,
    avgNdbi: 0.21,
    priorityLevel: 'Prioritas 2 (Tinggi)',
    suggestedAction: 'Optimalisasi sempadan sungai (Kanal Banjir Barat/Timur) dan taman lingkungan perumahan.'
  },
  {
    clusterId: 3,
    name: 'Klaster 3: Penyangga Perbukitan Hijau (Cool Sink)',
    districts: ['Gajahmungkur', 'Banyumanik', 'Gunungpati', 'Mijen'],
    avgLst: 29.5,
    avgNdvi: 0.58,
    avgNdbi: -0.08,
    priorityLevel: 'Penyangga Hijau',
    suggestedAction: 'Konservasi ketat resapan air, moratorium alih fungsi lahan sawah dan hutan lindung hulu.'
  }
];

export const MOCK_POST_MITIGATION_RECORDS: PostMitigationRecord[] = [
  {
    id: 'pm-1',
    wilayah: 'Semarang Tengah (Koridor Pandanaran)',
    actionTaken: 'Penanaman 120 Pohon Trembesi & Perlebaran Jalur Hijau Pedestrian',
    targetIntervention: 'Peningkatan Kanopi Vegetasi',
    periodBefore: 'Juni 2024',
    periodAfter: 'Juni 2026',
    lstBefore: 39.8,
    lstAfter: 37.4,
    ndviBefore: 0.08,
    ndviAfter: 0.22,
    rthPctBefore: 6.2,
    rthPctAfter: 11.5,
    aiPredictedLst: 37.6,
    deviation: -0.2, // Actual was 0.2 cooler than AI expected
    isAnomaly: false,
    dlhInspector: 'Budi Santoso, S.T. (Dinas Lingkungan Hidup)',
    dlhEvaluationNotes: 'Penurunan suhu permukaan mencapai 2.4°C. Efektivitas peneduhan kanopi sangat terasa bagi pedestrian pada jam 11:00-14:00 WIB.',
    efficacyRating: 'Sangat Efektif'
  },
  {
    id: 'pm-2',
    wilayah: 'Semarang Utara (Buffer Pelabuhan Tanjung Emas)',
    actionTaken: 'Sabuk Hijau Mangrove 15.000 Bibit & Penanaman Cemara Udang',
    targetIntervention: 'Sabuk Pesisir (Coastal Green Belt)',
    periodBefore: 'Mei 2024',
    periodAfter: 'Juni 2026',
    lstBefore: 39.1,
    lstAfter: 37.9,
    ndviBefore: 0.09,
    ndviAfter: 0.18,
    rthPctBefore: 7.0,
    rthPctAfter: 12.8,
    aiPredictedLst: 38.0,
    deviation: -0.1,
    isAnomaly: false,
    dlhInspector: 'Ir. Ahmad Zaini (DLH Bidang Konservasi)',
    dlhEvaluationNotes: 'Mangrove tumbuh baik, namun sebagian cemara udang di sempadan timur terdampak abrasi dan debu kontainer.',
    efficacyRating: 'Efektif'
  },
  {
    id: 'pm-3',
    wilayah: 'Genuk (Kawasan Industri Terboyo)',
    actionTaken: 'Penerapan Cat Atap Reflektif (Cool Roof) 8 Kompleks Pergudangan',
    targetIntervention: 'Material Albedo Tinggi',
    periodBefore: 'Juli 2025',
    periodAfter: 'Juni 2026',
    lstBefore: 38.9,
    lstAfter: 37.2,
    ndviBefore: 0.06,
    ndviAfter: 0.07,
    rthPctBefore: 4.8,
    rthPctAfter: 5.1,
    aiPredictedLst: 35.8,
    deviation: 1.4, // actual 37.2 vs predicted 35.8 -> Deviation > 1.0 = Anomaly!
    isAnomaly: true,
    dlhInspector: 'Siti Rahma, M.Sc. (Pengawas Pengendalian Dampak Lingkungan DLH)',
    dlhEvaluationNotes: 'Terdeteksi deviasi anomali (+1.4°C lebih tinggi dari prediksi model AI). Penyebab: intensitas emisi truk kontainer dan debu batubara menempel pada cat reflektif sehingga albedo menurun.',
    efficacyRating: 'Cukup'
  }
];
